### ISSUE TITLE
hackagebot does not notice publishes of previous (package) candidates

### ISSUE THREAD

**Issue by lspitzner** [lfairy/hircine#5]
possibly because publishing a candidate (i.e. turning the candidate package into a proper new package version) does not update the timestamp of the publishing, so the recent-package list (which seems to be strictly chronological by that timestamp) receives changes not only like `push_front` but potentially also like `insert`.

Feel free to forward this issue to hackage.. :-)

(also, nice to see the bot running again in a non-spammy fashion.)

**Comment by lambda-fairy** [comment]
Hackagebot does deal with new packages appearing in the middle of the feed: https://github.com/lfairy/hircine/blob/c574197/brigitte/Utils.hs#L218

But if too many other packages are uploaded in the meantime then the published candidate might never show up on the list in the first place. That would explain the behavior you're seeing.

Would you like to report this bug to Hackage? I'm busy with work at the moment and don't have the time to investigate.

**Comment by lambda-fairy** [comment]
@mniip runs Hackagebot now, and their instance doesn't use this code base. If you're still encountering this behavior, please raise the issue with them.
